name: BanCrates
description: ${project.description}
main: plus.crates.CratesPlus
version: ${project.version}
author: Connor Linfoot, Rozipp
softdepend: [HolographicDisplays,IndividualHolograms]
commands:
  bancrate:
    description: Main BanCrates command
    aliases: [bcrates,crates]
permissions:
  cratesplus.admin:
    default: op
  cratesplus.updates:
    default: op